# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '8.1'
pod 'GoogleMaps'
# xcodeproj '/Users/Sam/Desktop/LoginMap/Traverse/Traverse'

target 'Traverse' do
	pod 'Sodium',:git => 'https://github.com/jedisct1/swift-sodium.git'
end

target 'TraverseTests' do

end
